version: '2'
#networks:
#  mongodb_net:
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.213.0/24
    #       gateway: 192.168.213.1
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    #hostname: mongodb
    volumes:
      - ./db/mongo:/data/db
    ports:
      - 27017:27017

  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    container_name: adminmongo
    environment:
      - PORT=8082
      - CONN_NAME=mongodb
      - DB_HOST=mongodb
    links:
      - mongodb

  # mongoclient:
  #   image: mongoclient/mongoclient:latest
  #   container_name: mongoclient
  #   #hostname: mongoclient
  #   links:
  #     - mongodb
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 3300:3000

# volumes:
#   data: {}
